"""Constants for agent verification and scoring."""

# Instrumental detection thresholds
INSTRUMENTALNESS_THRESHOLD = 0.5
SPEECHINESS_THRESHOLD = 0.33

# Distraction scoring
DISTRACTION_SCORE_REJECTION_THRESHOLD = 0.7
DISTRACTION_SCORE_SPEECHINESS_WEIGHT = 0.4
DISTRACTION_SCORE_INSTRUMENTALNESS_WEIGHT = 0.3
DISTRACTION_SCORE_ENERGY_WEIGHT = 0.2
DISTRACTION_SCORE_EXPLICIT_PENALTY = 0.1

# BPM validation range
MIN_VALID_BPM = 60
MAX_VALID_BPM = 200
