"""Constants for agent verification and scoring."""

# Instrumental detection thresholds
INSTRUMENTALNESS_THRESHOLD = 0.5
SPEECHINESS_THRESHOLD = 0.33

# Distraction scoring
DISTRACTION_SCORE_REJECTION_THRESHOLD = 0.7
DISTRACTION_SCORE_SPEECHINESS_WEIGHT = 0.4
DISTRACTION_SCORE_INSTRUMENTALNESS_WEIGHT = 0.3
DISTRACTION_SCORE_ENERGY_WEIGHT = 0.2
DISTRACTION_SCORE_EXPLICIT_PENALTY = 0.1

# BPM validation range
MIN_VALID_BPM = 60
MAX_VALID_BPM = 200

# Energy constraints
FOCUS_MODE_MAX_ENERGY = 0.7  # Avoid high-intensity for Focus mode
RELAX_MODE_MAX_ENERGY = 0.6
SLEEP_MODE_MAX_ENERGY = 0.3
MEDITATION_MODE_MAX_ENERGY = 0.4

# Tempo constraints (BPM)
RELAX_MODE_TEMPO_MIN = 60.0
RELAX_MODE_TEMPO_MAX = 90.0
SLEEP_MODE_TEMPO_MIN = None  # No minimum tempo for sleep mode
SLEEP_MODE_TEMPO_MAX = 60.0  # Slow tempo for sleep mode
MEDITATION_MODE_TEMPO_MAX = 70.0
FOCUS_MODE_TEMPO_MIN = 120.0
FOCUS_MODE_TEMPO_MAX = 140.0
